name: Deploy to AUR
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Latest Upstream Version Tag
        run: |
          LATEST_VER=$(git ls-remote --tags https://github.com/FN-FAL113/server-picker-x.git | awk -F/ '{print $3}' | grep -v '\^{}' | sed 's/^v//' | sort -V | tail -n1)
          echo "Latest found version is: $LATEST_VER"
          sed -i "s/^pkgver=.*/pkgver=$LATEST_VER/" PKGBUILD

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v3
        with:
          pkgname: server-picker-x-git
          PKGBUILD: ./PKGBUILD
          SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_username: ${{ secrets.AUR_COMMIT_USERNAME }}
          commit_email: ${{ secrets.AUR_COMMIT_EMAIL }}
          updpkgsums: true
