name: Deploy to AUR
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # MANDATORY: Needed for git describe to see tags

      - name: Calculate Version and Update PKGBUILD
        run: |
          # Calculate the version using git history
          VERSION=$(git describe --long --tags --always | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g')
          echo "Calculated version: $VERSION"
          
          # Replace the pkgver() function block with a static pkgver variable
          # This range-based sed command finds from 'pkgver()' to the closing '}' and replaces it
          sed -i '/pkgver()/,/}/c\pkgver='"$VERSION" PKGBUILD

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v3
        with:
          pkgname: server-picker-x-git
          PKGBUILD: ./PKGBUILD
          SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_username: "***REMOVED***"
          commit_email: "***REMOVED***"
          updpkgsums: true
